"""
┌─────────────────────────────────────┐
│            Fame2PyGen               │
│         FAME → Python               │
│    Auto-Generated Pipeline         │
└─────────────────────────────────────┘

This file was automatically generated by Fame2PyGen
Contains the conversion pipeline from FAME script to Python
"""
import polars as pl
import formulas
df = pl.DataFrame({
    'date': pl.date_range('2019-01-01', '2025-01-01', '1mo'),
    '1': pl.Series('1', range(1, 74)),
    '12': pl.Series('12', range(1, 74)),
    '2': pl.Series('2', range(1, 74)),
    '3': pl.Series('3', range(1, 74)),
    '4': pl.Series('4', range(1, 74)),
    '5': pl.Series('5', range(1, 74)),
    'v123': pl.Series('v123', range(1, 74)),
    'v143': pl.Series('v143', range(1, 74)),
})
# ---- DECLARE SERIES ----
# ---- COMPUTATIONS ----
a = formulas.SUM_HORIZONTAL(df, ['v143', '12'])
b = formulas.SUM_HORIZONTAL(df, ['v143', '2'])
d = formulas.SUM_HORIZONTAL(df, ['v123', '1'])
e = formulas.SUM_HORIZONTAL(df, ['v123', '2'])
f = formulas.SUM_HORIZONTAL(df, ['v123', '3'])
g = formulas.SUM_HORIZONTAL(df, ['v123', '4'])
h = formulas.SUM_HORIZONTAL(df, ['v123', '5'])
pa = formulas.SUM_HORIZONTAL(df, ['v143', '4'])
pb = formulas.SUM_HORIZONTAL(df, ['v143', '1'])
pd = formulas.SUM_HORIZONTAL(df, ['v123', '3'])
pe = formulas.SUM_HORIZONTAL(df, ['v123', '4'])
pf = formulas.SUM_HORIZONTAL(df, ['v123', '5'])
pg = formulas.SUM_HORIZONTAL(df, ['v123', '1'])
ph = formulas.SUM_HORIZONTAL(df, ['v123', '2'])
hxz = formulas.SUM_HORIZONTAL(df, [])
c1 = formulas.SUM_HORIZONTAL(df, [])
aa = formulas.SUM_HORIZONTAL(df, ['a'])
bb = formulas.SUM_HORIZONTAL(df, ['aa', 'a'])
print('Computation finished')